{{- if or (not ( include "valheim.server.useExistingSecret" .)) (not (include "valheim.supervisor.useExistingSecret" .)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "valheim.fullname" . }}
  labels:
    {{- include "valheim.labels" . | nindent 4 }}
type: Opaque
data:
{{- if not (include "valheim.server.useExistingSecret" .) }}
  serverPassword: {{ include "valheim.server.password" . }}
{{- end -}}
{{- if not (include "valheim.supervisor.useExistingSecret" .) }}
  supervisorPassword: {{ include "valheim.supervisor.password" . }}
{{- end -}}
{{- end -}}
