{{- if and .Values.persistence.worldData.enabled (not .Values.persistence.worldData.existingClaim) (eq .Values.persistence.worldData.type "pvc")}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "valheim.fullname" . }}-world-data
  labels:
    {{- include "valheim.labels" . | nindent 4 }}
  {{- with .Values.persistence.worldData.pvc.annotations  }}
  annotations:
    {{- toYaml . | indent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.persistence.worldData.pvc.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.worldData.pvc.size | quote }}
  {{- if .Values.persistence.worldData.pvc.storageClassName }}
  storageClassName: {{ .Values.persistence.worldData.pvc.storageClassName }}
  {{- end -}}
  {{- with .Values.persistence.worldData.pvc.selectorLabels }}
  selector:
    matchLabels:
      {{- toYaml . | indent 6 }}
  {{- end }}
{{- end -}}
